sudo: required
services:
  - docker

before_install:
  - docker build -t saurabhsingh121/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true saurabhsingh121/react-test npm test

after_success:
  - docker build -t saurabhsingh121/multi-client ./client
  - docker build -t saurabhsingh121/multi-nginx ./nginx
  - docker build -t saurabhsingh121/multi-server ./server
  - docker build -t saurabhsingh121/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push saurabhsingh121/multi-client
  - docker push saurabhsingh121/multi-nginx
  - docker push saurabhsingh121/multi-server
  - docker push saurabhsingh121/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-031421005385"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
